//


BASICS OF ARDUINO PROGRAMMING:

Programming
 - Giving a set of instructions to a computer to execute.
 - Set of Instructions
 - Mental process of thinking up instructions to give to a machine

Coding
 - the process of transforming those ideas into a written language that a computer can understand.



Algorithm
- a set of finite rules or instructions to be followed in calculations or other problem-solving operations



INPUT - ALGORITHM (PROCESS) - OUTPUT

BASIC FLOWCHARTS

