DAY 2 ROBOTICS SEMINAR:

littleBits are colorful modular electronics Bits that snap together easily using small magnets to build fully-fledged
and functioning inventions.

The kits help make learning about circuitry and electronics fun and imaginative, so they can be used in classrooms and homes.

They're ideal for situations where you want to incorporate STEM education using a circuit kit.

The top side of the Bit is where the name is

Bits snap together with magnets. The magnets are always right - these will not snap together if in the wrong way.

Bits are grouped into four categories that are color coded - Power, Wire, Input, Output.

Power (Blue) - needed in every circuit and it is the start of all your students creation


